---
title: "DataGet"
author: "Dingyi Fang"
date: "4/14/2020"
output: html_document
---
#Read File Part
```{r path}
#[Diane]
img_dir <- '../../Done/Processed'
dir_path <- 'F:/server_output/processed/v11/Alclat2_stem.DONEGOOD.HANNAH.9.26/v11.0_0_1_900'
dir_split <- strsplit(dir_path,"/")[[1]]
version_name <- dir_split[length(dir_split)-2]
folder_name <- dir_split[length(dir_split)-1]#Alclat2_stem.DONEGOOD.HANNAH.9.26
folder_name_short <- strsplit(folder_name,".", fixed = TRUE)[[1]][1]#Alclat2_stem. fixed=TRUE to avoid interpreting "." as a regex
output_dir <- 'F:/emb_data'

#use the below arguments and save different csv file
use_true_tif <- TRUE #(TRUE):use true labels tif . (FALSE): use predict.tif 
#default is to plot tp emb.
plot_fn <- TRUE #(TRUE):plot fn emb. from false_positive_index.txt 
plot_fp <- FALSE
```

```{r read_tif}
library(bioimagetools)
#Read Data from TIFF file
pred_tiff = bioimagetools::readTIF(file.path(dir_path,'predict.tif'))
num_imgs <- dim(pred_tiff)[3]
row_num  <- dim(pred_tiff)[1]
col_num  <- dim(pred_tiff)[2] 
#get the embolism time data.
all_files <- list.files(file.path(img_dir,folder_name), pattern = '.png')
#get the idx name correct one in R
tp_img_idx <- as.vector(unlist(read.csv(file.path(dir_path,'true_positive_index.txt'),header = FALSE)))+1
#how many tp img in there
tp_num <- length(tp_img_idx)
```
#Processing the tiff into matrix pixel value
```{r tif_to_mat}
#column data for X and row data for Y
num = 1
plot_mat_all <- data.frame()#3 cols: row,col,Z
for (j in tp_img_idx) {
 plot_mat_j <- which(abs(pred_tiff[,,j]-1)!=0 , arr.ind = T)
 plot_mat_j <- data.frame(plot_mat_j)
 plot_mat_j$Z <- num
 plot_mat_all <- rbind(plot_mat_all,plot_mat_j)
 num <- num+ 1
}
```
#Processing the time list
```{r time_list}
#get the photo taken time
date_time_list = NULL
#initial the start time 
for (file in all_files) {
  time_str = unlist(strsplit(file, split = '.png'))
  #put all year month day in formate
  Year = substr(time_str,1,4)
  Month = substr(time_str,5,6)
  Day = substr(time_str,7,8)
  YMD = paste(Year,Month,Day,sep = '-')
  Hour = substr(time_str,10,11)
  Minute = substr(time_str,12,13)
  Secs = substr(time_str,14,15)
  HMS = paste(Hour,Minute,Secs, sep = ':')
  date_time = paste(YMD,HMS,sep = ' ')
  date_time_list = c(date_time_list,date_time)
}
#compute the relative time
date_time_list = date_time_list[1:num_imgs+1]
start_time = date_time_list[1]
diff_time_list = NULL
for (date_time in date_time_list) {
  diff_time = difftime(date_time,start_time, units = 'mins')
  diff_time_list = c(diff_time_list, diff_time)
}
diff_time_list_int <- floor(diff_time_list)
#put in the data frame to show table
number_emb = seq(1,tp_num)
embolism_time <- date_time_list[tp_img_idx]
diff_time_list_tp <- diff_time_list_int[tp_img_idx]
embolism_table <-  data.frame(embolism_time,diff_time_list_tp,number_emb)
colnames(embolism_table) <- c('embolism_time','time_since_start(mins)','number_emb')
```
#merge the two dataframe togther 
```{r merge_df}
plot_mat_time <- merge(plot_mat_all,embolism_table, by.x= 'Z', by.y= 'number_emb',all.x = TRUE)#5 cols: Z,row,col,embolism_time, time_since_start(mins)
```

```{r save_csv}
#Transform into csv formate
#[Diane]
if(!file.exists(output_dir)){
  dir.create(output_dir)
}
if(!file.exists(file.path(output_dir,version_name))){
  dir.create(file.path(output_dir,version_name))
}
if (!file.exists(file.path(output_dir,version_name,folder_name_short))){
    dir.create(file.path(output_dir,version_name,folder_name_short))
}
write.csv2(plot_mat_time,file = file.path(output_dir,version_name,folder_name_short,'emb_points_time.csv'),row.names = TRUE)
```

#NO need to run if its just get the csv, need to run it for shiny app
```{r shiny_data}
#data to feed image to plot
sum_tiff <- array(rep(0,row_num*col_num),dim = c(row_num,col_num))
plot_tiff <- array(rep(0, row_num*col_num*tp_num), dim=c(row_num, col_num, tp_num))
i = 1
for (number in tp_img_idx) {
  sum_tiff <- sum_tiff + pred_tiff[,,number]
  sum_tiff <- abs(sum_tiff -1)
  #make the mat sparse to easy plot
  plot_tiff[,,i] <- sum_tiff
  i = i+1
}

#save the data needed in shiny app
save(num_imgs,row_num,col_num,date_time_list, diff_time_list_int, embolism_table,  plot_mat_all, plot_tiff,  file = file.path(output_dir,version_name,folder_name_short,'shinydata.RData'))
```



